branch-defaults:
  flask-app:
    environment: softcon-leveldesign-flask-dev
  master:
    environment: softcon-leveldesign-flask-dev
    group_suffix: null
environment-defaults:
  softcon-leveldesign-flask-dev:
    branch: null
    repository: null
global:
  application_name: softcon-leveldesign-flask
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
